### ISSUE TITLE
Python 2 and 3 Compatible

### ISSUE THREAD

**Issue by search5** [search5/solrpy#42]
solrpy module, this enhancement is required to operate in the Python 2 and Python 3.

**Comment by shireen91** [comment]
is this module supported for python 3.6?

**Comment by search5** [comment]
@shireen91 No, it will not work normally. I downloaded this project again and modified it to work in Python 2 and 3, but the final porting failed because some code in the test case was dependent on Python 2.x.

We have improved it to work on this module to run in Python 3.4 ~ 3.6 for 6 hours at midnight UTC + 9 hours.

You can download it from http://github.com/search5/solrpy3.

**Comment by bkhouri** [comment]
Is there an ETA on when this ticket will be completed as python2 will be EOL in 2020.

https://legacy.python.org/dev/peps/pep-0373/
https://pythonclock.org/
