### ISSUE TITLE
Add LICENSE and include in MANIFEST?

### ISSUE THREAD

**Issue by pmlandwehr** [search5/solrpy#44]
Hey-lo,

I'm building a version of `solrpy` using [`conda`](http://conda.pydata.org/) for [conda-forge](http://conda-forge.github.io/). When possible, we try to include a link to the license file in the `meta.yaml` specification for the build; doing so requires the license be in the repository and that it be indexed in [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options) file so that it gets included in the source distribution. Would you consider adding a separate copy of the license info outside of the metadata where it's currently living and including it in the manifest?

**Comment by pmlandwehr** [comment]
You shouldn't if you don't want to! Including an explicit license file will help us out with our automated processing and license storage, but it isn't critical.

**Comment by search5** [comment]
> You shouldn't if you don't want to! Including an explicit license file will help us out with our automated processing and license storage, but it isn't critical.

I included the license file separately. I hope it will be of help.

**Comment by pmlandwehr** [comment]
Thanks!
