### ISSUE TITLE
In an array field, only the first element is returned in 0.9.8 version

### ISSUE THREAD

**Issue by nimishck** [search5/solrpy#49]
https://github.com/edsu/solrpy/blob/af58e5617eea15fa51a87e5453e6bb313ab15040/solr/core.py#L1056

This line is returning only the 0th element of the array field. Please remove the `[0]` subscript at the end of this line.

Should read:
`node.final = [node_data(cnode) for cnode in node.children]`

This works correctly in 0.9.7 version.

**Comment by search5** [comment]
I've worked on that patch, and I've modified it by patching it to work with Python 3.
